IMAGE_TOPIC = '/usb_cam/image_raw/compressed'
CMD_VEL = 'cmd_vel'
BOUNDING_BOXES = 'darknet_ros/bounding_boxes'
STATE_TOPIC = 'master/state'
AMCL_LOC = 'amcl_pose'
DEPTH_CAMERA = 'camera/depth/image_raw/compressed'
TRASH_TOPIC = 'litter_picker/vision'
